{{- $chartName := include "task-liberator.name" . -}}
{{- $tracingUrl := include "task-liberator.tracingUrl" . -}}
{{- $metricsUrl := include "task-liberator.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  JOB_SERVICE_URL: {{ .Values.rasterCommon.serviceUrls.jobManager | quote }}
  HEARTBEAT_ENABLED: {{ .Values.env.heartbeat.enabled | quote }}
  HEARTBEAT_FAILED_DURATION_MS: {{ .Values.env.heartbeat.failedDurationMs | quote }}
  HEARTBEAT_SERVICE_URL: {{ .Values.rasterCommon.serviceUrls.heartbeatManager | quote }}
  UPDATE_TIME_ENABLED: {{ .Values.env.updateTime.enabled | quote }}
  UPDATE_TIME_FAILED_DURATION_SEC: {{ .Values.env.updateTime.failedDurationSec | quote }}
  UPDATE_TIME_TASK_TYPES: {{ .Values.env.updateTime.taskTypes | quote }}
  UPDATE_TIME_IGNORED_TASK_TYPES: {{ .Values.env.updateTime.ignoredTaskTypes | quote }}
  EXPIRATION_STATUS_ENABLED: {{ .Values.env.expirationStatus.enabled | quote }}
  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.shouldResetTimeout | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }} 
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}  
{{- end }}
