global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}
  baseUrls:
    jobManager: 'http://job-service-url'
    heartbeatManager: 'http://heartbeat-service-url'

authentication:
  ca:
    enabled: true
    useExternal: false
    externalSecretName: ""
  ssl:
    enabled: true
    useExternal: false
    externalSecretName: ""

# ====================================================================================================
# Local certificate files variables
# ====================================================================================================

local:
  certs:
    ca: "certs/ca.crt"
    ssl: "certs/openssl.cnf"


enabled: true
environment: 'development'
replicaCount: 1
initialDelaySeconds: 60
nodePort: 30030 #for minikube deployment only

cloudProvider:
  dockerRegistryUrl: 'my-registry-url.io'
  flavor: 'openshift'
  imagePullSecretName: 'my-registry-secret'


cron:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  restartPolicy: Never

image:
  repository: 'task-liberator-registry'
  tag: 'latest'

env:
  port: 8080
  targetPort: 8080
  protocol: 'TCP'
  openApiFilPath: './openapi3.yaml'
  logLevel: 'info'
  tracing:
    enabled: false
    url: 'http://localhost:55681/v1/trace'
  metrics:
    enabled: false
    url: 'http://localhost:55681/v1/metrics'
  heartbeat:
    enabled: true
    failedDurationMs: 1000
  updateTime:
    enabled: true
    failedDurationSec: 300
    taskTypes: []
    ignoredTaskTypes: []
  expirationStatus:
    enabled: true    
  httpRetry:
    attempts: 3
    delay: 'exponential'
    shouldResetTimeout: true

resources:
  enabled: true
  value:
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'

route:
  enabled: false
  path: /

ingress:
  enabled: false
  path: /
  host: 'localhost'
  cors:
    enabled: true
    origin: '*'
